openapi: 3.0.3
info:
  title: LogicalModels Enumeration API
  description: API endpoint providing an enumeration of all available Logical Model
    schemas
  version: 1.0.0
paths:
  /LogicalModels.schema.json:
    get:
      summary: Get enumeration of all Logical Model schemas
      description: Returns a list of all available Logical Model schemas with metadata
      responses:
        '200':
          description: Successfully retrieved logical_model enumeration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EnumerationResponse'
              example: &id001
                type: logical_model
                count: 13
                schemas:
                - filename: StructureDefinition-DVC.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-DVC.schema.json
                  title: DVC
                  description: Data elements for Digital Vaccination Certificate.
                  url: ./StructureDefinition-DVC.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/DVC
                  propertyCount: 9
                - filename: StructureDefinition-VaccineDetailsSD.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-VaccineDetailsSD.schema.json
                  title: DVC Vaccine Details with Selective Disclosure
                  description: DVC Vaccine Details with Selective Disclosure
                  url: ./StructureDefinition-VaccineDetailsSD.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/VaccineDetailsSD
                  propertyCount: 13
                - filename: StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json
                  title: DVC HCERT Payload for PreQual DB
                  description: DVC payload for a minimal DVC for use within an HCERT
                    Payload using the WHO PreQual Vaccine Database
                  url: ./StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/DVCMinVaccineDetailsPreQual
                  propertyCount: 7
                - filename: StructureDefinition-HealthLinkPayload.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-HealthLinkPayload.schema.json
                  title: Health Link Payload (DRAFT)
                  description: 'Health Link Payload (DRAFT)


                    A Health Link URI is generated from this payload according to
                    the algorithm documented [here](https://build.fhir.org/ig/HL7/smart-health-cards-and-links/links-specification.html#smart-health-links-sharing-application-generates-a-smart-health-link-uri)



                    '
                  url: ./StructureDefinition-HealthLinkPayload.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/HealthLinkPayload
                  propertyCount: 7
                - filename: StructureDefinition-VaccineDetails.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-VaccineDetails.schema.json
                  title: DVC - Vaccine Details
                  description: Vaccine Data elements for the Digital Vaccination Certificates
                  url: ./StructureDefinition-VaccineDetails.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/VaccineDetails
                  propertyCount: 6
                - filename: StructureDefinition-DVCMin.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-DVCMin.schema.json
                  title: DVC HCERT Payload
                  description: Mininmial DVC payload for use within an HCERT Payload
                  url: ./StructureDefinition-DVCMin.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/DVCMin
                  propertyCount: 8
                - filename: StructureDefinition-DVCMinVaccineDetails.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-DVCMinVaccineDetails.schema.json
                  title: DVC HCert Vaccine Details (Minimal)
                  description: DVC Vaccine Details for a ininmial DVC payload for
                    use within an HCERT Payload
                  url: ./StructureDefinition-DVCMinVaccineDetails.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/DVCMinVaccineDetails
                  propertyCount: 7
                - filename: StructureDefinition-PreQualDVC.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-PreQualDVC.schema.json
                  title: PreQual
                  description: Data elements for the Digital Vaccine Certificate using
                    WHO Vaccine PreQualification database
                  url: ./StructureDefinition-PreQualDVC.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/PreQualDVC
                  propertyCount: 9
                - filename: StructureDefinition-SmartHealthLink.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-SmartHealthLink.schema.json
                  title: Smart Health Link (DRAFT)
                  description: 'Smart Health Link URI (DRAFT)


                    Logical Model to represent a SMART Health Link as its URI.  It
                    is generated from the content of the SMART Health Link Payload.



                    '
                  url: ./StructureDefinition-SmartHealthLink.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/SmartHealthLink
                  propertyCount: 1
                - filename: StructureDefinition-VerifiableHealthLinkPayload.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-VerifiableHealthLinkPayload.schema.json
                  title: Verifiable Health Link Payload (DRAFT)
                  description: 'Verifiable Health Link Payload (DRAFT)


                    This logical model constrains the Health Link Payload for a Verifiable
                    Health Link

                    '
                  url: ./StructureDefinition-VerifiableHealthLinkPayload.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/VerifiableHealthLinkPayload
                  propertyCount: 7
                - filename: StructureDefinition-DVCMinPreQual.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-DVCMinPreQual.schema.json
                  title: ''
                  description: DVC payload mininmized  for use within an HCERT Payload
                    with the WHO PreQual Vaccine Database
                  url: ./StructureDefinition-DVCMinPreQual.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/DVCMinPreQual
                  propertyCount: 8
                - filename: StructureDefinition-SMARTHealthLinkPayload.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-SMARTHealthLinkPayload.schema.json
                  title: SMART Health Link Payload (DRAFT)
                  description: 'SMART Health Link Payload (DRAFT)


                    This logical model constrains the Health Link Payload for a SMART
                    Health Link


                    A SMART Health Link URI is generated from this payload according
                    to the algorithm documented [here](https://build.fhir.org/ig/HL7/smart-health-cards-and-links/links-specification.html#smart-health-links-sharing-application-generates-a-smart-health-link-uri)


                    '
                  url: ./StructureDefinition-SMARTHealthLinkPayload.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/SMARTHealthLinkPayload
                  propertyCount: 7
                - filename: StructureDefinition-PreQualVaccineDetails.schema.json
                  id: http://smart.who.int/trust-phw/StructureDefinition-PreQualVaccineDetails.schema.json
                  title: PreQual - Vaccine Details
                  description: Vaccine Data elements from the Pre Qual Database
                  url: ./StructureDefinition-PreQualVaccineDetails.schema.json
                  logicalModelUrl: http://smart.who.int/trust-phw/StructureDefinition/PreQualVaccineDetails
                  propertyCount: 6
components:
  schemas:
    EnumerationResponse:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: '#/LogicalModels.schema.json'
      title: Logical Model Enumeration Schema
      description: JSON Schema defining the structure of the Logical Model enumeration
        endpoint response
      type: object
      properties:
        type:
          type: string
          const: logical_model
          description: The type of schemas enumerated (logical_model)
        count:
          type: integer
          description: Total number of schemas available
        schemas:
          type: array
          description: Array of available schemas
          items:
            type: object
            properties:
              filename:
                type: string
                description: Schema filename
              id:
                type: string
                description: Schema $id
              title:
                type: string
                description: Schema title
              description:
                type: string
                description: Schema description
              url:
                type: string
                description: Relative URL to the schema file
              logicalModelUrl:
                type: string
                description: FHIR canonical URL of the Logical Model
              propertyCount:
                type: integer
                description: Number of properties in the Logical Model
            required:
            - filename
            - title
            - url
      required:
      - type
      - count
      - schemas
      example: *id001
