openapi: 3.0.3
info:
  title: DVC HCERT Payload API
  description: Mininmial DVC payload for use within an HCERT Payload
  version: 1.0.0
paths:
  /StructureDefinition-DVCMin.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-DVCMin
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-DVCMin.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-DVCMin
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-DVCMin.schema.json
components:
  schemas:
    StructureDefinition-DVCMin:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust-phw/StructureDefinition-DVCMin.schema.json
      title: DVC HCERT Payload
      description: Mininmial DVC payload for use within an HCERT Payload
      type: object
      properties:
        n:
          type: string
          description: Person name
        dob:
          type: string
          format: date
          description: Date of birth in YYYY-MM-DD format
        s:
          type: string
          description: Sex
        ntl:
          type: string
          description: Nationality
        nid:
          type: string
          description: National Identification Document
        ndt:
          $ref: ValueSet-v2-0203.schema.json
          description: National ID Document Type
        gn:
          type: string
          description: Parent or Guardian Name
        v:
          type: array
          items:
            $ref: http://smart.who.int/trust-phw/StructureDefinition-DVCMinVaccineDetails.schema.json
          minItems: 1
          description: Vaccine Details
      required:
      - n
      - dob
      - v
      fhir:logicalModel: http://smart.who.int/trust-phw/StructureDefinition/DVCMin
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
