openapi: 3.0.3
info:
  title: DVC HCERT Payload for PreQual DB API
  description: DVC payload for a minimal DVC for use within an HCERT Payload using
    the WHO PreQual Vaccine Database
  version: 1.0.0
paths:
  /StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-DVCMinVaccineDetailsPreQual
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-DVCMinVaccineDetailsPreQual.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-DVCMinVaccineDetailsPreQual
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json
components:
  schemas:
    StructureDefinition-DVCMinVaccineDetailsPreQual:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust-phw/StructureDefinition-DVCMinVaccineDetailsPreQual.schema.json
      title: DVC HCERT Payload for PreQual DB
      description: DVC payload for a minimal DVC for use within an HCERT Payload using
        the WHO PreQual Vaccine Database
      type: object
      properties:
        vp:
          type: string
          description: ICVP Product Catalog ID
        dt:
          type: string
          format: date
          description: Date of vaccination, YYYY-MM-DD format
        cn:
          type: string
          description: Name of supervising clinician
        is:
          type: string
          description: Certificate issuer id (referenced organization)
        bo:
          type: string
          description: Batch No
        vls:
          type: string
          format: date
          description: Certificate Validity periods start date
        vle:
          type: string
          format: date
          description: Certificate Validity periods end date
      required:
      - vp
      - dt
      - bo
      fhir:logicalModel: http://smart.who.int/trust-phw/StructureDefinition/DVCMinVaccineDetailsPreQual
      fhir:parent: http://smart.who.int/trust-phw/StructureDefinition/DVCMinVaccineDetails
