openapi: 3.0.3
info:
  title: DVC - Vaccine Details API
  description: Vaccine Data elements for the Digital Vaccination Certificates
  version: 1.0.0
paths:
  /StructureDefinition-VaccineDetails.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-VaccineDetails
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-VaccineDetails.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-VaccineDetails
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-VaccineDetails.schema.json
components:
  schemas:
    StructureDefinition-VaccineDetails:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust-phw/StructureDefinition-VaccineDetails.schema.json
      title: DVC - Vaccine Details
      description: Vaccine Data elements for the Digital Vaccination Certificates
      type: object
      properties:
        productID:
          type: object
          description: 'Vaccine product information (note: use InventoryItem in FHIR
            R6)'
        date:
          type: string
          format: date
          description: Date of vaccine
        issuer:
          type: object
          description: Relevant authoring reponsible for issuing the certificate,
            or for overseeing the administration center
        clinicianName:
          type: string
          description: Name of supervising clinician, or relevant authority responsible
            for issuing this certificate, or for overseeing the administering centre
        batchNo:
          type: object
          description: Batch No
        validityPeriod:
          type: object
          description: Certificate validity period
      required:
      - productID
      - date
      - batchNo
      fhir:logicalModel: http://smart.who.int/trust-phw/StructureDefinition/VaccineDetails
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
