openapi: 3.0.3
info:
  title: DVC API
  description: Data elements for Digital Vaccination Certificate.
  version: 1.0.0
paths:
  /StructureDefinition-DVC.schema.json:
    get:
      summary: JSON Schema definition for the Logical Model StructureDefinition-DVC
      description: This endpoint serves the JSON Schema definition for the Logical
        Model StructureDefinition-DVC.
      responses:
        '200':
          description: The JSON Schema for StructureDefinition-DVC
          content:
            application/schema+json:
              schema:
                $ref: ./StructureDefinition-DVC.schema.json
components:
  schemas:
    StructureDefinition-DVC:
      $schema: https://json-schema.org/draft/2020-12/schema
      $id: http://smart.who.int/trust-phw/StructureDefinition-DVC.schema.json
      title: DVC
      description: Data elements for Digital Vaccination Certificate.
      type: object
      properties:
        name:
          type: string
          description: The full name of the client
        dob:
          type: string
          format: date
          description: Date of Birth
        sex:
          type: string
          description: Sex
        nationality:
          type: string
          description: Nationality
        nid:
          type: object
          description: National Identification Document
        ndt:
          $ref: ValueSet-v2-0203.schema.json
          description: National ID Document Type
        guardian:
          type: string
          description: Name of Parent or Guardian
        issuer:
          type: object
          description: Document issuer
        vaccineDetails:
          type: array
          items:
            $ref: http://smart.who.int/trust-phw/StructureDefinition-VaccineDetails.schema.json
          minItems: 1
          description: Vaccine Details
      required:
      - name
      - dob
      - vaccineDetails
      fhir:logicalModel: http://smart.who.int/trust-phw/StructureDefinition/DVC
      fhir:parent: http://hl7.org/fhir/StructureDefinition/Base
